# TensorFlow Quantitative Finance general math functions.

licenses(["notice"])

package(default_visibility = ["//tf_quant_finance:__subpackages__"])

py_library(
    name = "math",
    srcs = ["__init__.py"],
    srcs_version = "PY2AND3",
    deps = [
        "//tf_quant_finance/math/interpolation",
        "//tf_quant_finance/math/pde",
        "//tf_quant_finance/math/random",
    ],
)
