version = 1

test_patterns = ["tf_quant_finance/**/*_test.py"]

exclude_patterns = [
    "api_docs/**",
    "third_party/sobol_data/**"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
