licenses(["notice"])

exports_files(["LICENSE"])

py_library(
    name = "tf_quant_finance",
    srcs = ["__init__.py"],
    srcs_version = "PY2AND3",
    visibility = ["//visibility:public"],
    deps = [
        "//tf_quant_finance/math",
        "//tf_quant_finance/models",
        "//tf_quant_finance/rates",
        "//tf_quant_finance/volatility",
    ],
)
