# Pricing platform

licenses(["notice"])

package(default_visibility = ["//visibility:public"])

py_library(
    name = "pricing_platform",
    srcs = ["__init__.py"],
    srcs_version = "PY3",
    deps = [
        "//tf_quant_finance/experimental/pricing_platform/framework",
        "//tf_quant_finance/experimental/pricing_platform/instrument_protos",
    ],
)
