# Staging for the new models interface

licenses(["notice"])

package(default_visibility = ["//tf_quant_finance:__subpackages__"])

py_library(
    name = "models_v2",
    srcs = ["__init__.py"],
    srcs_version = "PY2AND3",
    deps = [
        ":ito_process",
    ],
)

py_library(
    name = "ito_process",
    srcs = ["ito_process.py"],
    srcs_version = "PY2AND3",
    deps = [],
)
