# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tf_quant_finance/experimental/pricing_platform/instrument_protos/all_instruments.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'tf_quant_finance/experimental/pricing_platform/instrument_protos/all_instruments.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tf_quant_finance.experimental.pricing_platform.instrument_protos import american_equity_option_pb2 as tf__quant__finance_dot_experimental_dot_pricing__platform_dot_instrument__protos_dot_american__equity__option__pb2
from tf_quant_finance.experimental.pricing_platform.instrument_protos import interest_rate_swap_pb2 as tf__quant__finance_dot_experimental_dot_pricing__platform_dot_instrument__protos_dot_interest__rate__swap__pb2
from tf_quant_finance.experimental.pricing_platform.instrument_protos import forward_rate_agreement_pb2 as tf__quant__finance_dot_experimental_dot_pricing__platform_dot_instrument__protos_dot_forward__rate__agreement__pb2
from tf_quant_finance.experimental.pricing_platform.instrument_protos import swaption_pb2 as tf__quant__finance_dot_experimental_dot_pricing__platform_dot_instrument__protos_dot_swaption__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nVtf_quant_finance/experimental/pricing_platform/instrument_protos/all_instruments.proto\x12@tf_quant_finance.experimental.pricing_platform.instrument_protos\x1a]tf_quant_finance/experimental/pricing_platform/instrument_protos/american_equity_option.proto\x1aYtf_quant_finance/experimental/pricing_platform/instrument_protos/interest_rate_swap.proto\x1a]tf_quant_finance/experimental/pricing_platform/instrument_protos/forward_rate_agreement.proto\x1aOtf_quant_finance/experimental/pricing_platform/instrument_protos/swaption.proto\"\xda\x03\n\nInstrument\x12p\n\x12interest_rate_swap\x18\x01 \x01(\x0b\x32R.tf_quant_finance.experimental.pricing_platform.instrument_protos.InterestRateSwapH\x00\x12x\n\x16\x66orward_rate_agreement\x18\x02 \x01(\x0b\x32V.tf_quant_finance.experimental.pricing_platform.instrument_protos.ForwardRateAgreementH\x00\x12^\n\x08swaption\x18\x03 \x01(\x0b\x32J.tf_quant_finance.experimental.pricing_platform.instrument_protos.SwaptionH\x00\x12x\n\x16\x61merican_equity_option\x18\x04 \x01(\x0b\x32V.tf_quant_finance.experimental.pricing_platform.instrument_protos.AmericanEquityOptionH\x00\x42\x06\n\x04typeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tf_quant_finance.experimental.pricing_platform.instrument_protos.all_instruments_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INSTRUMENT']._serialized_start=519
  _globals['_INSTRUMENT']._serialized_end=993
# @@protoc_insertion_point(module_scope)
