# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tf_quant_finance/experimental/pricing_platform/instrument_protos/american_equity_option.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'tf_quant_finance/experimental/pricing_platform/instrument_protos/american_equity_option.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tf_quant_finance.experimental.pricing_platform.instrument_protos import business_days_pb2 as tf__quant__finance_dot_experimental_dot_pricing__platform_dot_instrument__protos_dot_business__days__pb2
from tf_quant_finance.experimental.pricing_platform.instrument_protos import currencies_pb2 as tf__quant__finance_dot_experimental_dot_pricing__platform_dot_instrument__protos_dot_currencies__pb2
from tf_quant_finance.experimental.pricing_platform.instrument_protos import date_pb2 as tf__quant__finance_dot_experimental_dot_pricing__platform_dot_instrument__protos_dot_date__pb2
from tf_quant_finance.experimental.pricing_platform.instrument_protos import decimal_pb2 as tf__quant__finance_dot_experimental_dot_pricing__platform_dot_instrument__protos_dot_decimal__pb2
from tf_quant_finance.experimental.pricing_platform.instrument_protos import metadata_pb2 as tf__quant__finance_dot_experimental_dot_pricing__platform_dot_instrument__protos_dot_metadata__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n]tf_quant_finance/experimental/pricing_platform/instrument_protos/american_equity_option.proto\x12@tf_quant_finance.experimental.pricing_platform.instrument_protos\x1aTtf_quant_finance/experimental/pricing_platform/instrument_protos/business_days.proto\x1aQtf_quant_finance/experimental/pricing_platform/instrument_protos/currencies.proto\x1aKtf_quant_finance/experimental/pricing_platform/instrument_protos/date.proto\x1aNtf_quant_finance/experimental/pricing_platform/instrument_protos/decimal.proto\x1aOtf_quant_finance/experimental/pricing_platform/instrument_protos/metadata.proto\"\xb2\x06\n\x14\x41mericanEquityOption\x12\x16\n\x0eshort_position\x18\x01 \x01(\x08\x12[\n\x0b\x65xpiry_date\x18\x02 \x01(\x0b\x32\x46.tf_quant_finance.experimental.pricing_platform.instrument_protos.Date\x12\\\n\x08\x63urrency\x18\x03 \x01(\x0e\x32J.tf_quant_finance.experimental.pricing_platform.instrument_protos.Currency\x12\x0e\n\x06\x65quity\x18\x04 \x01(\t\x12\x62\n\x0f\x63ontract_amount\x18\x05 \x01(\x0b\x32I.tf_quant_finance.experimental.pricing_platform.instrument_protos.Decimal\x12Y\n\x06strike\x18\x06 \x01(\x0b\x32I.tf_quant_finance.experimental.pricing_platform.instrument_protos.Decimal\x12x\n\x17\x62usiness_day_convention\x18\x08 \x01(\x0e\x32W.tf_quant_finance.experimental.pricing_platform.instrument_protos.BusinessDayConvention\x12\x65\n\rbank_holidays\x18\t \x01(\x0e\x32N.tf_quant_finance.experimental.pricing_platform.instrument_protos.BankHolidays\x12\x17\n\x0fsettlement_days\x18\n \x01(\x05\x12\x66\n\x08metadata\x18\x0b \x01(\x0b\x32T.tf_quant_finance.experimental.pricing_platform.instrument_protos.InstrumentMetadata\x12\x16\n\x0eis_call_option\x18\x0c \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tf_quant_finance.experimental.pricing_platform.instrument_protos.american_equity_option_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AMERICANEQUITYOPTION']._serialized_start=571
  _globals['_AMERICANEQUITYOPTION']._serialized_end=1389
# @@protoc_insertion_point(module_scope)
