# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tf_quant_finance/experimental/pricing_platform/instrument_protos/currencies.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'tf_quant_finance/experimental/pricing_platform/instrument_protos/currencies.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nQtf_quant_finance/experimental/pricing_platform/instrument_protos/currencies.proto\x12@tf_quant_finance.experimental.pricing_platform.instrument_protos*\xdf\x01\n\x08\x43urrency\x12\x16\n\x12\x43URRENCY_UNDEFINED\x10\x00\x12\x07\n\x03USD\x10\x01\x12\x07\n\x03GBP\x10\x02\x12\x07\n\x03\x45UR\x10\x03\x12\x07\n\x03JPY\x10\x04\x12\x07\n\x03\x41UD\x10\x05\x12\x07\n\x03NZD\x10\x06\x12\x07\n\x03\x43\x41\x44\x10\x07\x12\x07\n\x03\x43HF\x10\x08\x12\x07\n\x03NOK\x10\t\x12\x07\n\x03SEK\x10\n\x12\x07\n\x03\x44KK\x10\x0b\x12\x07\n\x03MXN\x10\x0c\x12\x07\n\x03\x43NY\x10\r\x12\x07\n\x03RUB\x10\x0e\x12\x07\n\x03HKD\x10\x0f\x12\x07\n\x03SGD\x10\x10\x12\x07\n\x03TRY\x10\x11\x12\x07\n\x03KRW\x10\x12\x12\x07\n\x03ZAR\x10\x13\x12\x07\n\x03INR\x10\x14\x12\x07\n\x03\x42RL\x10\x15\x42\x02P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tf_quant_finance.experimental.pricing_platform.instrument_protos.currencies_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001'
  _globals['_CURRENCY']._serialized_start=152
  _globals['_CURRENCY']._serialized_end=375
# @@protoc_insertion_point(module_scope)
