# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tf_quant_finance/experimental/pricing_platform/instrument_protos/daycount_conventions.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'tf_quant_finance/experimental/pricing_platform/instrument_protos/daycount_conventions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n[tf_quant_finance/experimental/pricing_platform/instrument_protos/daycount_conventions.proto\x12@tf_quant_finance.experimental.pricing_platform.instrument_protos*\x85\x01\n\x12\x44\x61yCountConvention\x12 \n\x1c\x44\x41Y_COUNT_CONVENTION_UNKNOWN\x10\x00\x12\x16\n\x12\x41\x43TUAL_ACTUAL_ISDA\x10\x01\x12\x0e\n\nACTUAL_360\x10\x02\x12\x0e\n\nACTUAL_365\x10\x03\x12\x15\n\x11\x43ONVENTION_30_360\x10\x04\x42\x02P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tf_quant_finance.experimental.pricing_platform.instrument_protos.daycount_conventions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001'
  _globals['_DAYCOUNTCONVENTION']._serialized_start=162
  _globals['_DAYCOUNTCONVENTION']._serialized_end=295
# @@protoc_insertion_point(module_scope)
