# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tf_quant_finance/experimental/pricing_platform/instrument_protos/period.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'tf_quant_finance/experimental/pricing_platform/instrument_protos/period.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nMtf_quant_finance/experimental/pricing_platform/instrument_protos/period.proto\x12@tf_quant_finance.experimental.pricing_platform.instrument_protos\"t\n\x06Period\x12Z\n\x04type\x18\x01 \x01(\x0e\x32L.tf_quant_finance.experimental.pricing_platform.instrument_protos.PeriodType\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05*S\n\nPeriodType\x12\x10\n\x0cTYPE_UNKNOWN\x10\x00\x12\x07\n\x03\x44\x41Y\x10\x01\x12\x08\n\x04WEEK\x10\x02\x12\t\n\x05MONTH\x10\x03\x12\x0b\n\x07QUARTER\x10\x04\x12\x08\n\x04YEAR\x10\x05\x42\x02P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tf_quant_finance.experimental.pricing_platform.instrument_protos.period_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001'
  _globals['_PERIODTYPE']._serialized_start=265
  _globals['_PERIODTYPE']._serialized_end=348
  _globals['_PERIOD']._serialized_start=147
  _globals['_PERIOD']._serialized_end=263
# @@protoc_insertion_point(module_scope)
