# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tf_quant_finance/experimental/pricing_platform/instrument_protos/swaption.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'tf_quant_finance/experimental/pricing_platform/instrument_protos/swaption.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tf_quant_finance.experimental.pricing_platform.instrument_protos import date_pb2 as tf__quant__finance_dot_experimental_dot_pricing__platform_dot_instrument__protos_dot_date__pb2
from tf_quant_finance.experimental.pricing_platform.instrument_protos import metadata_pb2 as tf__quant__finance_dot_experimental_dot_pricing__platform_dot_instrument__protos_dot_metadata__pb2
from tf_quant_finance.experimental.pricing_platform.instrument_protos import interest_rate_swap_pb2 as tf__quant__finance_dot_experimental_dot_pricing__platform_dot_instrument__protos_dot_interest__rate__swap__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nOtf_quant_finance/experimental/pricing_platform/instrument_protos/swaption.proto\x12@tf_quant_finance.experimental.pricing_platform.instrument_protos\x1aKtf_quant_finance/experimental/pricing_platform/instrument_protos/date.proto\x1aOtf_quant_finance/experimental/pricing_platform/instrument_protos/metadata.proto\x1aYtf_quant_finance/experimental/pricing_platform/instrument_protos/interest_rate_swap.proto\"\xb1\x02\n\x08Swaption\x12[\n\x0b\x65xpiry_date\x18\x02 \x01(\x0b\x32\x46.tf_quant_finance.experimental.pricing_platform.instrument_protos.Date\x12`\n\x04swap\x18\x03 \x01(\x0b\x32R.tf_quant_finance.experimental.pricing_platform.instrument_protos.InterestRateSwap\x12\x66\n\x08metadata\x18\x04 \x01(\x0b\x32T.tf_quant_finance.experimental.pricing_platform.instrument_protos.InstrumentMetadatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tf_quant_finance.experimental.pricing_platform.instrument_protos.swaption_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SWAPTION']._serialized_start=399
  _globals['_SWAPTION']._serialized_end=704
# @@protoc_insertion_point(module_scope)
